# Change these first
owner: greatnusa # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: GreatNusa - Web
    url: https://www.greatnusa.com
  - name: GreatNusa - API
    url: https://api.greatnusa.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #  cname: status.greatnusa.com
  baseUrl: /upptime
  logoUrl: https://www.greatnusa.com/GreatNusaLogoNew.png
  name: Upptime
  introTitle: "Upptime Status"
  introMessage: GreatNusa Uptime monitoring
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
